### PR TITLE
Rel/0.13.1

### PR DESCRIPTION
**Pull request by satra**
This PR is using a special branch from my nipype repo at the moment to test the build. We should do this before releasing a new version from master.

### CODE REVIEW

**Comment by satra** [comment]
@isuruf - here is the PR from the fork. 

circle passes now as i saw in my local test. but don't understand the travis error.

appveyor i'll try and fix - looks like an issue with the prov-feedstock on py27 for windows.

**Comment by isuruf** [comment]
Can you rerender?

**Comment by satra** [comment]
```
(dev36pype) [satra@warpspeed nipype-feedstock (rel/0.13.0)]$ conda update -n root conda-smithy
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /software/miniconda3:
#
conda-smithy              2.1.1                    py35_0    conda-forge
(dev36pype) [satra@warpspeed nipype-feedstock (rel/0.13.0)]$ conda-smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata ...........
Fetching package metadata ...........

Re-rendered with conda-smithy 2.1.1.

No changes made. This feedstock is up-to-date.
```

**Comment by isuruf** [comment]
Can you update conda-smithy to 2.3.0 and try?

**Comment by satra** [comment]
@isuruf - just did.

**Comment by isuruf** [comment]
travis failure is because of an anaconda.org error. @conda-forge/core, can you delete the duplicate package `osx-64/rdflib-4.2.2-py27_0.tar.bz2` at https://anaconda.org/conda-forge/rdflib/files ?

**Comment by ocefpaf** [comment]
I just deleted it. Let me know if it helps it here.

**Comment by isuruf** [comment]
@ocefpaf, it worked.

**Comment by satra** [comment]
woohoo - thanks for all your help. now i wait for the official release update to push and merge.

**Pull request merged**
