### PR TITLE
REL: 1.0.1 release

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by effigies** [comment]
PR created with `hub`:

```Python
git push -u origin rel/1.0.1
hub pull-request -m 'TEST: 1.0.1 release'
```

**Comment by effigies** [comment]
Tests passing. Good to go.

**Comment by mgxd** [comment]
ping @chrisfilo @satra

**Comment by effigies** [comment]
Before merging: if it makes life easier, I can add me and @mgxd to the maintainers list. (Anybody else?)

**Pull request merged**
