### PR TITLE
REL: 1.1.6

### PR DESCRIPTION
**Pull request by nipybot**
Updating feedstock to release branch

#### Environment

| Variable                    | Value                    |
|-----------------------------|--------------------------|
| `CIRCLE_PROJECT_USERNAME` | nipy |
| `CIRCLE_PROJECT_REPONAME` | nipype |
| `CIRCLE_BRANCH`           | rel/1.1.6           |
| `CIRCLE_TAG`              |               |

#### Calculated values

* URL = https://github.com/nipy/nipype/archive/rel/1.1.6.tar.gz
* SHA256 = `d20d1ac7869bc71904813fca955e60f3795ab72801f95b0bbebea79498d27e1d`

### CODE REVIEW

**Comment by effigies** [comment]
@conda-forge-admin Please rerender.

**Comment by effigies** [comment]
@satra or @mgxd Want to review? This makes sense to me from reading [Preprocessing selectors](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#preprocessing-selectors), and it builds, but a second pair of eyes would be nice.

**Comment by effigies** [comment]
@mgxd Good catch. Glad there's somebody who actually finishes reading a sentence.

**Comment by effigies** [comment]
If you're happy with this, want to merge? I'm not sure we can really test if it imposes the right constraints until a build is published.

**Comment by mgxd** [comment]
yeah let's do it - if things look off, we can always re-release and increment the build

**Pull request merged**
