### PR TITLE
tst: release 1.0.0

### PR DESCRIPTION
**Pull request by mgxd**

### CODE REVIEW

**Comment by effigies** [comment]
I started a Travis build on my allocation, in case that lets us jump the queue for OSX builds. https://travis-ci.org/effigies/nipype-feedstock/builds/333382502

**Comment by effigies** [comment]
@conda-forge-admin, please rerender.

**Comment by effigies** [comment]
Hmm. Don't think I can do that. Anyway, job's failing. Maybe @mgxd or @satra could make the bot do work for us.

**Comment by mgxd** [comment]
@effigies looks like your build jumped the queue, want to give it another go? If travis passes, we can merge nipy/nipype#2399 and update url/md5 to nipype's release tarball

**Comment by effigies** [comment]
Yup. https://travis-ci.org/effigies/nipype-feedstock/builds/333398751

OTOH, the number of nodes running OSX jobs has just been cut by a third. https://www.traviscistatus.com/

**Comment by effigies** [comment]
I think the scheduling algorithm is roughly round-robin on a per-allocation, which means that my top job is on equal footing with conda-forge's top job. And conda-forge has like 30-40 projects that are sitting and waiting for their turn to be the top job.

**Comment by effigies** [comment]
@mgxd Finished. You can release.

**Comment by effigies** [comment]
Hey, it passed! @satra @chrisfilo I think you need to merge, and we can get conda builds online.

**Comment by chrisfilo** [comment]
OMG - this is happening.

**Pull request merged**
